export enum FileExtensionEnum {
  PNG = 'png',
  JPG = 'jpg',
  JPEG = 'jpeg',
  SVG = 'svg',
  HEIC = 'heic',
  HEIF = 'heif',
  MP3 = 'mp3',
  MP4 = 'mp4',
  GIF = 'gif',
  WEBP = 'webp',
  XLS = 'xls',
  XLSX = 'xlsx',
  DOCX = 'docx',
  PPT = 'ppt',
  PPTX = 'pptx',
  PDF = 'pdf',
  JSON = 'json',
  XML = 'xml',
  CVS = 'cvs',
}
